services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    restart: "always"
    environment:
      - POSTGRES_DB=snyder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    ports:
      - 5432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
